### ISSUE TITLE
cachimo.clear() should also clear all timeouts

### ISSUE THREAD

**Issue by gr2m** [svipas/cachimo#1]
Hey Benas, thanks for the neat little key/value memory store!

I have one feature request: when testing with cachimo, the process will not end until all timeouts are done. It would be nice if `cachimo.clear()` would clear all timeouts, too. I could try to add that if this is within the scope of the library?

**Comment by svipas** [comment]
Hey @gr2m, sorry for late response.

Very good suggestion! I think we can store them inside `Set` or simple `Array`. I think it makes sense to have function `cachimo.terminate()` or `cachimo.stop()` which clears all timeouts, but all key/values will be inside cache. What do you think?

P.S. If you want you can open PR or I can do it. 👷

**Comment by gr2m** [comment]
Happy to send a PR :)

I think making `cachimo.clear()` also stop all timeouts would be good enough, at least for my use case. Or do you see a reason where you want to clear the cache but keep the timeouts intact?

**Comment by svipas** [comment]
@gr2m What I mean is `cachimo.clear()` will clear everything (keys/values and timeouts). But also we need to have `cachimo.terminate()` or `cachimo.stop()` which will clear only timeouts. It's good if developer want to keep keys/values, but want to stop/terminate all timeouts.

**Comment by gr2m** [comment]
If I understand you correctly, it would work like this?

```js
cachimo.put('key', 'value', 1000)
cachimo.stop()
setTimeout(() => {
  cachimo.get('key') // 1000
}, 2000)
```

calling `cachimo.stop()` would cancel all timeouts for data currently stored in cache? I still don't see a use case for that, I must miss something?

Okay if I go ahead and send a pull request to update `cachimo.clear()` only for now?

**Comment by svipas** [comment]
@gr2m Yeah for now update `cachimo.clear()`, but what I mean is `cachimo.stop()` will clear all timeouts not the data. Imagine you use `cachimo.put('key', 'value', 60e3);` which will remove your `key` with `value` after 60 seconds and you changed your mind and you want to keep that `key` with `value` so you use `cachimo.stop()` or `cachimo.terminate()` to clear all timeouts and your `key` with `value` will be available because it only clears timeouts not the data. So you can easily do again `cachimo.get('key');` to get `value`. This is only usable if timeouts are more than 1 minute. I even see it makes sense to have `cachimo.stop('key')` to stop not all timeouts but only for given `key`. But for now you can make only `cachimo.clear()` to clear all timeouts too.

But keep this issue open because of our discussion.

Thanks again @gr2m ! 👍

**Comment by svipas** [comment]
I already created and merged these PRs:

* https://github.com/svipben/cachimo/pull/2
* https://github.com/svipben/cachimo/pull/3

/cc @gr2m

**Comment by gr2m** [comment]
thanks a lot!
